server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://db:5432/tagmind_db
    username: tagmind_user
    password: tagmind_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT 설정
jwt:
  secret: ${JWT_SECRET:your-very-secret-key-that-is-at-least-256-bits-long}
  access-token-expiration-ms: 3600000 # 1시간 (밀리초)
  refresh-token-expiration-ms: 604800000 # 7일 (밀리초)