server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/**

# Eureka 설정 (서비스 디스커버리를 사용하지 않는 경우)
# eureka:
#   client:
#     enabled: false
