"""empty message

Revision ID: 6762abfe9807
Revises: 9a4319544195
Create Date: 2025-07-22 02:09:26.609730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6762abfe9807"
down_revision: Union[str, Sequence[str], None] = "9a4319544195"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE diaries SET updated_at = NOW() WHERE updated_at IS NULL")
    op.alter_column(
        "diaries",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
        existing_nullable=True,
        server_default=sa.func.now(),
        postgresql_using="updated_at",
        type_=sa.DateTime(timezone=True),
    )  # PostgreSQL의 경우
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
