"""Update Diary-Tag relationship

Revision ID: 9a4319544195
Revises: fee7bba7ef09
Create Date: 2025-07-21 14:21:23.975560

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9a4319544195"
down_revision: Union[str, Sequence[str], None] = "fee7bba7ef09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("diary_tags")
    op.create_table(
        "diary_tags",
        sa.Column("diary_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["diary_id"],
            ["diaries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("diary_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("diary_tags")
    op.create_table(
        "diary_tags",
        sa.Column("diary_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column(
            "source", sa.String(), nullable=True
        ),  # Re-add source column if needed for downgrade
        sa.ForeignKeyConstraint(
            ["diary_id"],
            ["diaries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("diary_id", "tag_id"),
    )
    # ### end Alembic commands ###
